### ISSUE TITLE
[BUG] Add-on load error since upgrading to Anki 2.1.42 (8eebfe18) 

### ISSUE THREAD

**Issue by andrewcrook** [yukach/anki21-addon-customize-sidebar#11]
Anki 2.1.42 (8eebfe18) 
Python 3.8.6 
Qt 5.14.2 
PyQt 5.14.2
macOS Big Sur 11.2.3 (20D91)
MacBook Pro with M1 SoC 16GB

**I am getting an error loading Anki**

```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Customize Sidebar⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 210, in loadAddons
  File "/Users/andrew/Library/Application Support/Anki2/addons21/1988760596/__init__.py", line 5, in <module>
    from . import customize_sidebar
  File "/Users/andrew/Library/Application Support/Anki2/addons21/1988760596/customize_sidebar.py", line 23, in <module>
    from aqt.browser import SidebarItem
ImportError: cannot import name 'SidebarItem' from 'aqt.browser' (/Applications/Anki.app/Contents/MacOS/aqt/browser.pyc)
```

**Comment by andrewcrook** [comment]
I tried the add-on on its own and got the same error

**Comment by husmle** [comment]
I had same problem

**Comment by husmle** [comment]
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Customize Sidebar⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 210, in loadAddons
  File "/Users/z/Library/Application Support/Anki2/addons21/1988760596/__init__.py", line 5, in <module>
    from . import customize_sidebar
  File "/Users/z/Library/Application Support/Anki2/addons21/1988760596/customize_sidebar.py", line 23, in <module>
    from aqt.browser import SidebarItem
ImportError: cannot import name 'SidebarItem' from 'aqt.browser' (/Applications/Anki.app/Contents/MacOS/aqt/browser.pyc)
⁩

**Comment by yukach** [comment]
As far as I see, the functionality of my addon has been added into anki
since version 41 !!! please check.

**Comment by Kezza6** [comment]
same issue here.  brand new download of Anki (not an update), first time trying to add the add-on.

> An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on. When loading '⁨Customize Sidebar⁩': ⁨Traceback (most recent call last): File "aqt\addons.py", line 210, in loadAddons File "C:\Users\kla30\AppData\Roaming\Anki2\addons21\1988760596\__init__.py", line 5, in <module> from . import customize_sidebar File "C:\Users\kla30\AppData\Roaming\Anki2\addons21\1988760596\customize_sidebar.py", line 23, in <module> from aqt.browser import SidebarItem ImportError: cannot import name 'SidebarItem' from 'aqt.browser' (C:\Program Files\Anki\aqt\browser.pyc) ⁩
