### ISSUE TITLE
AttributeError: 'Browser' object has no attribute 'CallbackItem'

### ISSUE THREAD

**Issue by ErezVolk** [yukach/anki21-addon-customize-sidebar#3]
Thanks for a very useful addon!

It looks like a recent Anki version broke something, and `self.CallbackItem` is gone. This is from Anki 2.1.17:

```
Caught exception:
Traceback (most recent call last):
  File "aqt/progress.py", line 73, in handler
  File "aqt/browser.py", line 1067, in deferredDisplay
  File "aqt/browser.py", line 1076, in buildTree
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-4>", line 2, in _stdTree
  File "anki/hooks.py", line 82, in decorator_wrapper
  File "anki/hooks.py", line 74, in repl
  File "/Users/erez/Library/Application Support/Anki2/addons21/1988760596/customize_sidebar.py", line 21, in my_stdTree
    item = self.CallbackItem(root, _("Marked"), self._filterFunc("tag:marked"))
AttributeError: 'Browser' object has no attribute 'CallbackItem'
```

**Comment by yukach** [comment]
Ok, thanks for feedback. I'll fix it.

**Comment by yukach** [comment]
Fixed. Please update the addon. If you come across any errors, let me know.

**Comment by ErezVolk** [comment]
Thank you!

**Comment by ErezVolk** [comment]
Works great! If I come across anything else, I'll let you know.
