### ISSUE TITLE
Bug when I open browser. 

### ISSUE THREAD

**Issue by loko-crypto** [yukach/anki21-addon-customize-sidebar#9]
Every time I try to enable this addon, I get this bug when I open the browser. I tried disabling "advanced browser" but I still get this same bug.  It goes away when I disable this addon. 

Debug info:
Anki 2.1.19 (3c8690ae) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=2

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 73, in handler
  File "aqt\browser.py", line 1068, in deferredDisplay
  File "aqt\browser.py", line 1077, in buildTree
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-30>", line 2, in _stdTree
  File "lib\site-packages\anki\hooks.py", line 82, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 74, in repl
  File "C:\Users\sos\AppData\Roaming\Anki2\addons21\1988760596\customize_sidebar.py", line 21, in my_stdTree
    item = self.CallbackItem(root, _("Marked"), self._filterFunc("tag:marked"))
AttributeError: 'AdvancedBrowser' object has no attribute 'CallbackItem'

**Comment by yukach** [comment]
ok ,thank you. I will look at it today. What is AdvancedBrowser? addon? If so, can you disable that addon and recheck.

**Comment by yukach** [comment]
yeap, my addon conflicts with the Advanced browser addon. Thus, you should use either mine or the Advanced browser addon. They cannot work the same time and I cannot fix it.

**Comment by yukach** [comment]
Also, did you restart anki after disabling addon?

**Comment by yukach** [comment]
What addon versions do you use? I would like to reproduce that issue on my side.

**Comment by yukach** [comment]
no reaction
